---
driver_plugin: docker

driver_config:
  require_chef_omnibus: latest
  use_sudo: false
  dns:
  - 208.67.222.222
  - 208.67.220.220

settings:
  parallel: true
  destroy: passing

platforms:
- name: centos-6.4

suites:
- name: dev
  run_list:
  - role[base]
  - role[dev]
  attributes:
    authorization:
      sudo:
        users: 
        - kitchen
- name: util
  run_list:
  - role[base]
  - role[util]
  attributes:
    authorization:
      sudo:
        users: 
        - kitchen
- name: media
  run_list:
  - role[base]
  - role[media]
  attributes:
    authorization:
      sudo:
        users: 
        - kitchen
