---
driver_plugin: docker

platforms:
- name: centos-6.4
  driver_config:
    image: centos:6.4
    platform: centos
    require_chef_omnibus: true
    use_sudo: false
    dns:
    - 208.67.222.222
    - 208.67.220.220

suites:
- name: dev
  run_list:
  - role[base]
  - role[app]
  attributes:
    authorization:
      sudo:
        users: 
        - kitchen
- name: util
  run_list:
  - role[base]
  - role[util]
  attributes:
    authorization:
      sudo:
        users: 
        - kitchen
- name: media
  run_list:
  - role[base]
  - role[media]
  attributes:
    authorization:
      sudo:
        users: 
        - kitchen
