---
driver_plugin: bluebox

driver_config:
  bluebox_customer_id: <%= ENV['BLUEBOX_CUSTOMER_ID'] %>
  bluebox_api_key: <%= ENV['BLUEBOX_API_KEY'] %>
  ssh_public_key: <%= File.expand_path('~/.ssh/id_rsa.pub') %>
  ssh_key: <%= File.expand_path('~/.ssh/id_rsa') %>
  require_chef_omnibus: true
 
platforms:
- name: sl-64
  driver_config:
    image_id: 99b819c4-5b8c-45a2-848b-b57153f587ca

suites:
- name: app_server
  run_list:
  - role[base]
  - role[app]
  attributes:
    authorization:
      sudo:
        users: 
        - kitchen
- name: util_server
  run_list:
  - role[base]
  - role[util]
  attributes:
    authorization:
      sudo:
        users: 
        - kitchen
